export const CONFIG = {
  tileSize: 60,
  viewport: { w: 12, h: 9 },
  town: { w: 24, h: 16 },
  floor: { w: 40, h: 28 },
  baseEnemyHp: 3,
  enemyAttack: 1,
  meleeDamage: 0,
  specialCost: 1,
  specialRange: 4,
  reviveHp: 2,
  logLimit: 6,
  lungCapacity: 10,
  inventorySlots: 12,
  carryWeightLimit: 28,
  fishUpgradeBase: 8,
  levelUpHpGain: 1,
  levelUpAtkEvery: 3,
  expBaseNext: 5,
  pressureEveryTurns: 8,
  hungerTickTurns: 3,
  thirstTickTurns: 2,
  staminaRecoverPerTurn: 1,
  projectileEffectMs: 420,
  damageEffectMs: 550,
  effectTickMs: 80,
};

export const ASSETS = {
  floor: "assets/floor.png",
  wall: "assets/wall.png",
  floor_cave: "assets/floor_cave.png",
  wall_cave: "assets/wall_cave.png",
  floor_ice: "assets/floor_ice.png",
  wall_ice: "assets/wall_ice.png",
  player: "assets/player.png",
  enemy: "assets/enemy.png",
  item: "assets/item.png",
  heal: "assets/heal.png",
  oxygen: "assets/oxygen.png",
  stairs: "assets/stairs.png",
  train: "assets/train.png",
  rest: "assets/rest.png",
  gate: "assets/gate.png",
  board: "assets/board.png",
};

export const DIRS = {
  ArrowUp: { x: 0, y: -1 },
  ArrowDown: { x: 0, y: 1 },
  ArrowLeft: { x: -1, y: 0 },
  ArrowRight: { x: 1, y: 0 },
};
